sudo: required
language: nodejs

services:
  - docker

branches:
  only:
    - master

install:
  - export AWS_ACCOUNT=123456789012

stages:
  - test
  - name: deploy
    if: branch = master && type = push

jobs:
  include:
    - stage: test
      script:
        - env
        - echo ${AWS_ACCOUNT}
        - echo ${TRAVIS_BUILD_ID}
    - stage: deploy
      script:
        - echo Deploying to ${AWS_ACCOUNT}