sudo: required
language: nodejs

services:
  - docker

branches:
  only:
    - master

jobs:
  include:
    - stage: install
      script:
        - export AWS_ACCOUNT=123456789012
    - stage: test
      script:
        - env
        - echo ${AWS_ACCOUNT}
        - echo ${TRAVIS_BUILD_ID}
    - stage: deploy
      if: branch = master && type = push
      script:
        - echo Deploying to ${AWS_ACCOUNT}